### ISSUE TITLE
Facebook are dropping the offline_access permission

### ISSUE THREAD

**Issue by larister** [dtompkins/fbcmd#13]
Apologies if this doesn't apply to this project but I just stumbled across it and wanted to give you a heads up about a potential issue.

Facebook have announced that they're dropping support for the offline_access permission:

https://developers.facebook.com/roadmap/offline-access-removal/

As of October 3rd, all existing offline_access access tokens will be given a 60 day expiry period. Once those have expired, you will need to retrieve long-lived (60 day) user access_tokens every 60 days.

Please feel free to get in touch if you want more details, I've been looking into this quite a bit recently and the documentation isn't always clear.

**Comment by bigomega** [comment]
@larister Wow, You came to close an issue from 12 years back… 😮
