### ISSUE TITLE
Not working as of 09.01.2015

### ISSUE THREAD

**Issue by orschiro** [dtompkins/fbcmd#17]
Hi @dtompkins,

I am not sure whether you are still working on fbcmd. However, it does not work anymore with the recent API of Facebook.

The commands `fbcmd go access` and `bcmd go auth` just lead to a blank page. 

Regards,

Robert

**Comment by dtompkins** [comment]
Yeah, I've heard... I just don't have any spare time to try to see if a
workaround is possible

**Comment by orschiro** [comment]
Thanks for clarifying!

I will use Pidgin with XMPP for now [1].

[1] https://www.facebook.com/sitetour/chat.php

**Comment by h1rule** [comment]
Please update it @dtompkins !

**Comment by bigomega** [comment]
The FBCMD (Facebook Command Line Interface) project is no longer active. You can still find the lukewarm corpse of the project at the links below.

from http://fbcmd.dtompkins.com/

**Comment by orschiro** [comment]
@bigomega Thanks for your updated information!

~ Robert

**Comment by heriipurnama** [comment]
omg...fbcmd is RIP. .. .
